version: '3.4'

services:
  scrapping-WoS:
    image: python-3.8
    container_name: scrapping-WoS
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5678:5678
    volumes:
      - ./code:/app/code
    command: python /app/code/main.py
    # command: tail -f /dev/null # keep open container 
